/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const before_Players_Create_Update = require('./code/before-players-create-update');
const before_Games_Create_Update = require('./code/before-games-create-update');
const on_Games_Start = require('./code/on-games-start');
const after_Results_Read = require('./code/after-results-read');

class tabla_multiplicarSrv extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'Players', async (request) => {
            await before_Players_Create_Update(request);
        });

        this.before(['CREATE', 'UPDATE'], 'Games', async (request) => {
            await before_Games_Create_Update(request);
        });

        this.on('start', 'Games', async (request) => {
            return on_Games_Start(request);
        });

        this.after('READ', 'Results', async (results, request) => {
            await after_Results_Read(results, request);
        });

        return super.init();
    }
}


module.exports = {
    tabla_multiplicarSrv
};